name: flutter_ta
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter_onboarding_slider: ^1.0.11
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.8
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  google_fonts: 6.1.0
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  audioplayers: ^6.0.0
  shared_preferences: ^2.0.8
  http: ^1.2.1
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl: ^0.17.0

flutter:
  fonts:
    - family: JakartaSans
      fonts:
        - asset: fonts/PlusJakartaSans-Regular.ttf
        - asset: fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: fonts/PlusJakartaSans-Regular.ttf
          weight: 400
  assets:
    - images/
    - images/kalma_logo.svg
    - images/kalma_logo_new.png
    - images/kalma_splash_bg.png
    - images/kalma_splash_bg_1.png
    - images/kalma_splashscreen.png
    - images/bgsplash.png
    - images/ellipse_bg_mobile_bottom.png
    - images/ellipse_bg_mobile_top.png
    - images/check_starts_shape.png
    - images/onboarding_1.png
    - images/onboarding_2.png
    - images/onboarding_3.png
    - images/onboarding_4.png
    - images/profile_icon.png
    - images/clear_icon.png
    - music_images/
    - assets/audio/
  uses-material-design: true